### PR TITLE
Fixes issue #10 .

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones I am seeing lots of white space entered. I am not sure how I can get rid of it in vim.

Until I fix it please use `?w=1` as earlier mentioned by @jakesmith ( Thank you ) 

https://github.com/auraphp/Aura.Dispatcher/pull/11/files?w=1

Have installed https://github.com/spf13/spf13-vim . I want to look more into it.

**Comment by pmjones** [comment]
Hey dude -- can you send a PR without the whitespace changes?

**Comment by harikt** [comment]
@pmjones sure.

**Comment by harikt** [comment]
New PR https://github.com/auraphp/Aura.Dispatcher/pull/12

**Pull request closed without merging**
