### PR TITLE
Jk3us tests

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
Fixes #23 , #24

**Comment by harikt** [comment]
Thank you @jk3us for the issues reported and further the PR with tests.

Thank you.

**Comment by harikt** [comment]
Scrutinize made B to C for the class Dispatcher :-/ .

**Comment by harikt** [comment]
@pmjones could you look into this and merge if ok?

**Comment by jk3us** [comment]
FYI, I've been playing with your fixed branch, and it seems to be working ok.

**Comment by harikt** [comment]
:+1:  . @pmjones merge ?

**Comment by harikt** [comment]
@pmjones ping ? Else I will merge in 2 days :) ( warning ) .

**Comment by pmjones** [comment]
No, not yet -- I still want to review it and see if it can be incorporated against the other packages. Sorry for the delay.

**Comment by harikt** [comment]
I was writing a mail to please consider looking at open PR .

Call me arrogant. But I hate long waiting PR's :-/ .

**Comment by harikt** [comment]
@pmjones ~ 3 months. Could you please find some time for this and make a release ?.

**Pull request closed without merging**
