### PR TITLE
Revert "Support __call magic method on objects"

### PR DESCRIPTION
**Pull request by pmjones**
Reverts auraphp/Aura.Dispatcher#21

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones why is this as a PR ?

**Comment by pmjones** [comment]
I just pressed the button to see what would happen 8-D

**Comment by harikt** [comment]
I guess it is due to you have already pushed the commits. ie why none seems changed in PR .

**Comment by harikt** [comment]
May be we can close this for now, and on a later time it will be handy . Thoughts ?

**Pull request merged**
